theme: jekyll-theme-minimal
title: Neil Joseph
description: I am your friendly neighbourhood Software Engineer, based in New Delhi, India. I have been switching tabs for over 6 years now and my ‘spidey senses’ work best while debugging code. 
logo: assets/img/logo.jpeg