theme: jekyll-theme-minimal
title: 
description: I appreciate you taking the time to review my resume! I'm excited about the possibility of collaborating with you. Please reach out to me via Email or LinkedIn.
